"""ibkr_ensure_tws.py — bring TWS to a logged-in state unattended, so the
NewsCrawler ibkr_news channel always has a live socket on :7496.

Idempotent: if 7496 is already open it exits immediately. Otherwise it launches
TWS, waits for the Swing login window, and drives an unattended login —
username/password from D:\\AIStock\\.env, 2FA via IBKR Mobile Authenticator TOTP
generated by AIStock's own shared.ibkr_launcher.current_totp_code() (reused,
not reimplemented).

Credential handling: no secret is stored in this file. Values are read from the
user's .env at runtime; the TOTP code is generated from IBKR_TOTP_SECRET. TWS is
configured ReadOnlyApi, so the socket can never place an order.

Intended to be run by the account owner's own scheduler (Task Scheduler at
logon, or as a pre-step in AIStock's daily_run) — NOT by NewsCrawler's crawl
process, which stays free of any credential handling.

Flow (rebuilt 2026-07-24 from a live end-to-end forensic — every screen below
was screenshot-verified that day):
  1. Window match is LANGUAGE-AGNOSTIC (title "Login"/"登录"/"Second Factor…"/
     "身份验证…") — the login screen keeps the last manually-selected language.
  2. Credential entry: click the username field (PROPORTIONAL coords — the
     window embeds a dynamic bulletin panel so its size varies, 1006x589 one
     day / 1062x620 the next; fixed pixels put the password into the visible
     username box on 2026-07-24), then TAB → password → ENTER, which removes
     the password-field and Log-In-button coordinates from the equation
     entirely (TAB order and default-button submit are stable).
  3. 2FA: the account's DEFAULT second factor is IB Key push ("Open the IBKR
     notification on your phone") with NO code field. The chain clicks
     "Change security device" → selects "Mobile Authenticator app" → OK →
     lands on "Enter Mobile Authenticator app code" (auto-focused input) →
     types the TOTP + ENTER. Each click is harmless on the screens where its
     target is absent, so the same blind chain works from any 2FA variant
     (push / device-select / direct code entry).
  4. The auth session dies in ~2-3 min ("Your connection was lost. Would you
     like to re-login?") — the chain runs with NO long pauses, and the retry
     pass clicks Re-login and goes again.

Swing exposes no child controls to UI automation (no Java Access Bridge), so
all targets are proportional click-points scaled from a 1062x620 reference
capture. Exit 0 = socket up, 1 = failed.

Usage:  python scripts/ibkr_ensure_tws.py
"""
import os
import socket
import subprocess
import sys
import time

TWS_EXE = r"D:\IBTWS\tws\tws.exe"
AISTOCK_DIR = "D:/AIStock"
PORT = 7496

# Proportional click-points, measured from a LIVE 1062x620 capture (2026-07-24).
# Scaled by the actual window rect at click time — the login window's size
# varies with the embedded bulletin panel, so absolute pixels are unreliable.
REF_W, REF_H = 1062, 620
P_USERNAME = (763, 294)        # username field center (login form)
P_RELOGIN_BTN = (517, 340)     # "Re-login" button of the connection-lost dialog
P_CHANGE_DEVICE = (746, 509)   # "Change security device" link (push screen)
P_DEVICE_AUTH_ROW = (892, 99)  # "Mobile Authenticator app" row (device select)
P_DEVICE_OK = (813, 321)       # OK button (device select)

# Any state of the login/2FA frame, both languages
_FRAME_TITLE_RE = r"^(Login|登录|Second Factor|第二|身份验证|双重)"

_SPECIAL = set("^+%~(){}[]")


def port_open(port=PORT, host="127.0.0.1", timeout=0.6) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def _load_env():
    sys.path.insert(0, AISTOCK_DIR)
    try:
        from dotenv import load_dotenv
        load_dotenv(os.path.join(AISTOCK_DIR, ".env"))
    except Exception:
        pass


def esc(s: str) -> str:
    return "".join("{" + c + "}" if c in _SPECIAL else c for c in s)


def do_login() -> bool:
    from pywinauto import Desktop, mouse
    from pywinauto.keyboard import send_keys
    from shared.ibkr_launcher import current_totp_code

    username = os.environ.get("IBKR_USERNAME", "")
    password = os.environ.get("IBKR_PASSWORD", "")
    if not username or not password:
        print("[err] IBKR_USERNAME / IBKR_PASSWORD missing from .env")
        return False

    # Wait for the login window (TWS cold start can take 20-40s).
    # 2026-07-24: title is LANGUAGE-DEPENDENT — the login screen keeps the last
    # manually-selected language ("Login" in English, "登录" in Chinese; the
    # 00:26 auto-restart that day logged "SPLASH 连接服务器" = Chinese UI live
    # in production). Anchored regex: the logged-in MAIN frame ("U... Interactive
    # Brokers" / "盈透…") never starts with either token, so this cannot match it.
    win = None
    for _ in range(60):
        try:
            w = Desktop(backend="uia").window(
                title_re=_FRAME_TITLE_RE, class_name="SunAwtFrame")
            if w.exists(timeout=1):
                win = w
                break
        except Exception:
            pass
        time.sleep(1.0)
    if win is None:
        print("[err] TWS login window never appeared")
        # Diagnostic: list what Swing frames WERE visible so a language/title
        # drift is identifiable from the log alone next time.
        try:
            titles = [w.window_text() for w in Desktop(backend="uia").windows()
                      if w.class_name() == "SunAwtFrame" and w.is_visible()]
            print(f"[err] visible SunAwtFrame titles: {titles!r}")
        except Exception:
            pass
        return False

    import re as _re
    _is_2fa = _re.compile(r"^(Second Factor|第二|身份验证|双重)")

    def _pclick(w, pt, wait=0.8):
        """Proportional click: scale the 1062x620 reference point by the LIVE
        window rect. The login window embeds a dynamic bulletin panel so its
        size varies run to run — absolute pixels put the password into the
        visible username field on 2026-07-24."""
        r = w.rectangle()
        mouse.click(coords=(r.left + round(pt[0] * r.width() / REF_W),
                            r.top + round(pt[1] * r.height() / REF_H)))
        time.sleep(wait)

    def _frame(iters=5):
        for _ in range(iters):
            try:
                w = Desktop(backend="uia").window(
                    title_re=_FRAME_TITLE_RE, class_name="SunAwtFrame")
                if w.exists(timeout=1):
                    return w
            except Exception:
                pass
            time.sleep(1.0)
        return None

    def _type_credentials(w):
        """Username click → TAB → password → ENTER. TAB order and the default
        Log-In button are layout-stable, so only ONE coordinate (the username
        field) is position-sensitive — and that one is proportional."""
        w.set_focus()
        time.sleep(0.5)
        _pclick(w, P_USERNAME, 0.5)
        send_keys("^a{DEL}", pause=0.04)
        send_keys(esc(username), pause=0.04, with_spaces=True)
        send_keys("{TAB}", pause=0.1)
        time.sleep(0.3)
        send_keys("^a{DEL}", pause=0.04)
        send_keys(esc(password), pause=0.04, with_spaces=True)
        send_keys("{ENTER}", pause=0.1)
        print("[ok] credentials submitted (username → TAB → ENTER)")

    if _is_2fa.match(win.window_text() or ""):
        # A prior partial run left TWS sitting at a 2FA screen — credentials
        # are already accepted; go straight to the 2FA chain below.
        print("[..] already at a 2FA screen — skipping credential entry")
    else:
        _type_credentials(win)

    for attempt in (1, 2):
        # Wait for either the API socket (no-2FA path) or a 2FA screen.
        twofa = None
        for _ in range(30):
            time.sleep(1.0)
            if port_open():
                print("[done] logged in without a 2FA prompt")
                return True
            w = _frame(1)
            if w is not None and _is_2fa.match(w.window_text() or ""):
                twofa = w
                break
        if twofa is None:
            if attempt == 1:
                # Submit may have been swallowed by the connection-lost dialog.
                # Clicking the Re-login spot is harmless on the plain form, and
                # ENTER-noise inside the dialog just triggers its default
                # (Re-login) button — both paths converge on a retryable state.
                w = _frame(3)
                if w is not None:
                    w.set_focus()
                    time.sleep(0.4)
                    _pclick(w, P_RELOGIN_BTN, 3.0)
                    w = _frame(3)
                    if w is not None and not _is_2fa.match(w.window_text() or ""):
                        _type_credentials(w)
                continue
            print("[err] no 2FA screen and no socket after submit")
            return False

        # 2FA chain (screenshot-verified 2026-07-24). The account's default
        # second factor is IB Key PUSH — a screen with NO code field, so the
        # old "wait for a code dialog and type the TOTP" approach typed into
        # the void. The blind sequence below is safe on ALL three variants:
        #   push screen         : clicks "Change security device" → device list
        #   device-select screen: first click hits empty space, then row + OK
        #   direct code entry   : clicks land on empty space / the input field
        # and every path converges on "Enter Mobile Authenticator app code"
        # with the input auto-focused.
        twofa.set_focus()
        time.sleep(0.3)
        _pclick(twofa, P_CHANGE_DEVICE, 1.5)
        _pclick(twofa, P_DEVICE_AUTH_ROW, 0.6)
        _pclick(twofa, P_DEVICE_OK, 1.8)
        code = current_totp_code()
        if not code:
            print("[err] current_totp_code() is None — check IBKR_TOTP_SECRET / pyotp")
            return False
        try:
            twofa.set_focus()
        except Exception:
            pass
        time.sleep(0.4)
        send_keys(code, pause=0.06)
        send_keys("{ENTER}", pause=0.1)
        print(f"[ok] TOTP submitted (attempt {attempt})")

        for _ in range(60):
            time.sleep(1.0)
            if port_open():
                print("[done] 7496 open — TWS logged in")
                return True

        # The auth session dies in ~2-3 min ("Your connection was lost") —
        # click Re-login and run the chain once more. TWS remembers the
        # credentials, so the retry re-enters at the 2FA screen directly.
        if attempt == 1:
            w = _frame(3)
            if w is not None:
                w.set_focus()
                time.sleep(0.4)
                _pclick(w, P_RELOGIN_BTN, 3.0)

    print("[err] 7496 never opened")
    return False


def warm_news_farm(timeout_total: int = 90) -> bool:
    """After a COLD login the IBKR news farm needs ~30-60s before
    reqHistoricalNews stops timing out (observed 2026-07-20: the daily_run
    that cold-logged-in pulled 26 ibkr_news items vs ~100 warm — the crawl
    started before the farm was ready). Probe reqHistoricalNews for a liquid
    conid (AAPL) until it RESPONDS (even an empty list = warm), bounded by
    timeout_total. Readonly, no credentials involved. Returns True when warm;
    False on timeout (non-fatal — the channel's own retry may still cope)."""
    import asyncio

    async def _probe() -> bool:
        from ib_insync import IB
        ib = IB()
        try:
            await ib.connectAsync("127.0.0.1", PORT, clientId=24,
                                  timeout=10, readonly=True)
        except Exception as exc:
            print(f"[warn] farm-warmup connect failed: {type(exc).__name__}")
            return False
        try:
            try:
                providers = await asyncio.wait_for(ib.reqNewsProvidersAsync(), 15)
            except Exception:
                return False
            codes = "+".join(p.code for p in providers)
            if not codes:
                return True   # no news subscriptions — nothing to warm
            deadline = time.time() + timeout_total
            attempt = 0
            while time.time() < deadline:
                attempt += 1
                try:
                    arts = await asyncio.wait_for(
                        ib.reqHistoricalNewsAsync(265598, codes, "", "", 5),
                        timeout=10)   # 265598 = AAPL conid
                    if arts is not None:
                        print(f"[ok] news farm warm after {attempt} probe(s)")
                        return True
                except Exception:
                    pass
                await asyncio.sleep(5)
            return False
        finally:
            try:
                ib.disconnect()
            except Exception:
                pass

    try:
        return asyncio.run(_probe())
    except Exception as exc:
        print(f"[warn] farm-warmup error: {type(exc).__name__}: {exc}")
        return False


def _tws_running() -> bool:
    """True if a tws.exe process already exists — avoid launching a second
    instance (which trips TWS's single-instance / Jts lock and pops a modal
    that steals focus). Windows tasklist; best-effort."""
    try:
        out = subprocess.run(
            ["tasklist", "/FI", "IMAGENAME eq tws.exe", "/NH"],
            capture_output=True, text=True, timeout=10)
        return "tws.exe" in (out.stdout or "").lower()
    except Exception:
        return False


def main() -> int:
    if port_open():
        print("[skip] 7496 already open — TWS already logged in")
        return 0
    if not os.path.exists(TWS_EXE):
        print(f"[err] TWS exe not found: {TWS_EXE}")
        return 1
    _load_env()
    # Only launch if no TWS is already running: a leftover / at-login instance
    # from a prior partial run has a closed API socket (so port_open() was
    # false) but launching a second one trips the single-instance lock.
    if _tws_running():
        print("[..] TWS already running (not logged in) — driving its login window")
    else:
        print(f"[..] launching TWS: {TWS_EXE}")
        try:
            subprocess.Popen([TWS_EXE], cwd=os.path.dirname(TWS_EXE))
        except Exception as exc:
            print(f"[err] failed to launch TWS: {exc}")
            return 1
    if not do_login():
        return 1
    # Cold login succeeded — warm the news farm so the crawl that follows
    # (daily_run 0b starts seconds later) gets full ibkr_news coverage
    # instead of the thin cold-farm harvest. Non-fatal on timeout.
    if not warm_news_farm():
        print("[warn] news farm still cold after warm-up window — "
              "ibkr_news may be thin this run (its retry may still cope)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
